insert into enemy_ship values(1, 'Aye Captain, Whats the bearing for Torpedo to fire (1-10)?','7');
insert into enemy_ship values(2, 'Captain, I suggest we fire multiple Torpedo this time. Whats the bearing(1-20)','13');
insert into enemy_ship values(3, 'Aye Captain, I can not listen the Submarine clear, please tell me depth as well to fire. Answer format: b-d where b range from 1- 20, d range from 1-250. Example: 5-10 ','7-9');
insert into enemy_ship values(4, 'Captain, we are close to enemy. This time I need depth only (1-100)','53');
insert into enemy_ship values(5, 'All ears we are in danger, Captain..shout bearing and depth: Answer format: b-d where b range from 1- 20, d range from 1-50. Example: 5-10 ','19-39');
insert into enemy_ship values(6, 'Captain, I hear something in Sonar, Tell me bearing to shoot? (23-34)','24');
insert into enemy_ship values(7, 'Captain, This seems easy hit. Suggest direction (N, W, S, E)','S');
insert into enemy_ship values(8, 'Captain, we are close to enemy. This time I need depth only (20-30)','27');
insert into enemy_ship values(9, 'Captain, we are close to enemy. This time I need depth only (50-70)','53');
insert into enemy_ship values(10,'Captain, we are close to enemy. This time I need depth only (8-10)','9');
insert into enemy_ship values(11, 'Aye Captain, Whats the bearing for Torpedo to fire (1-10)?','7');
insert into enemy_ship values(12, 'Captain, I suggest we fire multiple Torpedo this time. Whats the bearing(1-20)','13');
insert into enemy_ship values(13, 'Aye Captain, I can not listen the Submarine clear, please tell me depth as well to fire. Answer format: b-d where b range from 1- 20, d range from 1-250. Example: 5-10 ','7-9');
insert into enemy_ship values(14, 'Captain, we are close to enemy. This time I need depth only (1-100)','53');
insert into enemy_ship values(15, 'All ears we are in danger, Captain..shout bearing and depth: Answer format: b-d where b range from 1- 20, d range from 1-50. Example: 5-10 ','19-39');
insert into enemy_ship values(16, 'Captain, I hear something in Sonar, Tell me bearing to shoot? (23-34)','24');
insert into enemy_ship values(17, 'Captain, This seems easy hit. Suggest direction (N, W, S, E)','S');
insert into enemy_ship values(18, 'Captain, we are close to enemy. This time I need depth only (20-30)','27');
insert into enemy_ship values(19, 'Captain, we are close to enemy. This time I need depth only (50-70)','53');
insert into enemy_ship values(20,'Captain, we are close to enemy. This time I need depth only (8-10)','9');
insert into enemy_ship values(21, 'Aye Captain, Whats the bearing for Torpedo to fire (1-10)?','7');
insert into enemy_ship values(22, 'Captain, I suggest we fire multiple Torpedo this time. Whats the bearing(1-20)','13');
insert into enemy_ship values(23, 'Aye Captain, I can not listen the Submarine clear, please tell me depth as well to fire. Answer format: b-d where b range from 1- 20, d range from 1-250. Example: 5-10 ','7-9');
insert into enemy_ship values(24, 'Captain, we are close to enemy. This time I need depth only (1-100)','53');
insert into enemy_ship values(25, 'All ears we are in danger, Captain..shout bearing and depth: Answer format: b-d where b range from 1- 20, d range from 1-50. Example: 5-10 ','19-39');
insert into enemy_ship values(26, 'Captain, I hear something in Sonar, Tell me bearing to shoot? (23-34)','24');
insert into enemy_ship values(27, 'Captain, This seems easy hit. Suggest direction (N, W, S, E)','S');
insert into enemy_ship values(28, 'Captain, we are close to enemy. This time I need depth only (20-30)','27');
insert into enemy_ship values(29, 'Captain, we are close to enemy. This time I need depth only (50-70)','53');
insert into enemy_ship values(30,'Captain, we are close to enemy. This time I need depth only (8-10)','9');
